# Example secrets.toml for Streamlit Cloud
# Accessible in code via st.secrets

[app]
# default_model can be "Logistic Regression" or "Random Forest"
default_model = "Random Forest"

# Example for future API integrations:
# [openai]
# api_key = "your_openai_api_key"
